stages:        
  - build
 # - test
  #- deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:15
  script:
    - npm install
    - npm run build

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
